# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbaf9a2068f9fcae12d236d4bbdc0998e8594157b052dbd9490799eb258645524cb41a280f15eea3f5afcfe6f0e6aad00dce9d18738d6dab04a57abeff3d665b

test:
  secret_key_base: 086f61a51f680679cbef9bdc02d84322558beacc5a60d653285a5502c20d0e6785f73ac3a4656ec6e79b6d37093724bf5ea52fefd719a8eedc463259c4162795

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
